# Assignment: Data Wrangling
## `! git clone https://github.com/DS3001/wrangling`
## Do Q2, and one of Q1 or Q3.

**Q1.** Open the "tidy_data.pdf" document in the repo, which is a paper called Tidy Data by Hadley Wickham.

  1. Read the abstract. What is this paper about?
  - This paper looks at how tidying data makes cleaning it easier by using a simple structure where each variable is a column, each observation is a row, and each type of data goes in its own table. This setup makes it simpler to organize messy data and create tools that work well with tidy data, shown in a case study that avoids the usual boring data cleanup.
  2. Read the introduction. What is the "tidy data standard" intended to accomplish?
  - The "tidy data standard" is intended to simplify data cleaning and analysis by providing a consistent structure for organizing data. It makes it easier to work with and reduces the time spent on preparing the data. It also aims to facilitate the development of tools that work seamlessly together, allowing users to focus on solving the actual problem rather than dealing with issues of data formatting.
  3. Read the intro to section 2. What does this sentence mean: "Like families, tidy datasets are all alike but every messy dataset is messy in its own way." What does this sentence mean: "For a given dataset, it’s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general."
  - "Like families, tidy datasets are all alike but every messy dataset is messy in its own way" means that while tidy datasets are similar, they all have their own unique qualities and traits.
  - "For a given dataset, it’s usually easy to figure out what are observations and what are variables, but it is surprisingly difficult to precisely define variables and observations in general" means that it can be hard to create a general definition that applies to all datasets, but it is easy to identify those aspects of a dataset.
  4. Read Section 2.2. How does Wickham define values, variables, and observations?
  - Values - numbers or strings in a dataset
  - Variables - contains all values that measure the same underlying attribute (like height, temperature, duration) across units.
  - Observations -  contains all values measured on
the same unit (like a person, or a day, or a race) across attributes.
  5. How is "Tidy Data" defined in section 2.3?
  - Tidy Data: a dataset where:
    1. Each variable forms a column.
    2. Each observation forms a row.
    3. Each type of observational unit forms a table.

  6. Read the intro to Section 3 and Section 3.1. What are the 5 most common problems with messy datasets? Why are the data in Table 4 messy? What is "melting" a dataset?
  - The 5 most common problems with messy datasets:
    1. Column headers are values, not variable names
    2. Multiple variables are stored in one column
    3. Variables are stored in both rows and columns
    4. Multiple types of observational units are stored in the same table
    5. A single observational unit is stored in multiple tables
  - The data in table 4 are messy because the columns are values of a income that is not defined as a variable. You need a new column for income.
  - Melting a dataset: turning columns into rows; stacking it

  7. Why, specifically, is table 11 messy but table 12 tidy and "molten"?
  - In Table 11, the days are listed along the top as values. Table 12 improves this by combining the days into a single variable, date.
  8. Read Section 6. What is the "chicken-and-egg" problem with focusing on tidy data? What does Wickham hope happens in the future with further work on the subject of data wrangling?
  - The chicken-and-egg issue: "if tidy data is only as useful as the tools that work with it, then tidy tools will be inextricably linked to tidy data." Wickham hopes future work will expand on the tidy data framework to create better tools and storage strategies. He also wants to apply ideas from fields like human-computer interaction to improve how we understand and design data tools, and he sees potential for new frameworks to handle tasks like parsing, error correction, and missing data.

**Q2.** This question provides some practice cleaning variables which have common problems.
1. Numeric variable: For `./data/airbnb_hw.csv`, clean the `Price` variable as well as you can, and explain the choices you make. How many missing values do you end up with? (Hint: What happens to the formatting when a price goes over 999 dollars, say from 675 to 1,112?)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
df = pd.read_csv('/content/airbnb_hw.csv', low_memory=False)
print( df.shape, '\n')
df.head()

(30478, 13)

,Host Id,Host Since,Name,Neighbourhood,Property Type,Review Scores Rating (bin),Room Type,Zipcode,Beds,Number of Records,Number Of Reviews,Price,Review Scores Rating
0,5162530,NaN,1 Bedroom in Prime Williamsburg,Brooklyn,Apartment,NaN,Entire home/apt,11249.0,1.0,1,0,145,NaN
1,33134899,NaN,"Sunny, Private room in Bushwick",Brooklyn,Apartment,NaN,Private room,11206.0,1.0,1,1,37,NaN
2,39608626,NaN,Sunny Room in Harlem,Manhattan,Apartment,NaN,Private room,10032.0,1.0,1,1,28,NaN
3,500,6/26/2008,Gorgeous 1 BR with Private Balcony,Manhattan,Apartment,NaN,Entire home/apt,10024.0,3.0,1,0,199,NaN
4,500,6/26/2008,Trendy Times Square Loft,Manhattan,Apartment,95.0,Private room,10036.0,3.0,1,39,549,96.0

In [6]:
price = df['Price']
price.unique()

price = price.str.replace(',','') # this deletes the commas
print( price.unique() , '\n')
price = pd.to_numeric(price,errors='coerce') # the value for price becomes a numeric value not a string
print( price.unique() , '\n')
print( 'Total missing: ', sum( price.isnull() ) ) # counts and prints the missing values

['145' '37' '28' '199' '549' '149' '250' '90' '270' '290' '170' '59' '49'
 '68' '285' '75' '100' '150' '700' '125' '175' '40' '89' '95' '99' '499'
 '120' '79' '110' '180' '143' '230' '350' '135' '85' '60' '70' '55' '44'
 '200' '165' '115' '74' '84' '129' '50' '185' '80' '190' '140' '45' '65'
 '225' '600' '109' '1990' '73' '240' '72' '105' '155' '160' '42' '132'
 '117' '295' '280' '159' '107' '69' '239' '220' '399' '130' '375' '585'
 '275' '139' '260' '35' '133' '300' '289' '179' '98' '195' '29' '27' '39'
 '249' '192' '142' '169' '1000' '131' '138' '113' '122' '329' '101' '475'
 '238' '272' '308' '126' '235' '315' '248' '128' '56' '207' '450' '215'
 '210' '385' '445' '136' '247' '118' '77' '76' '92' '198' '205' '299'
 '222' '245' '104' '153' '349' '114' '320' '292' '226' '420' '500' '325'
 '307' '78' '265' '108' '123' '189' '32' '58' '86' '219' '800' '335' '63'
 '229' '425' '67' '87' '1200' '158' '650' '234' '310' '695' '400' '166'
 '119' '62' '168' '340' '479' '43' '395' '144' '52' '47' '529' '187' '209'
 '233' '82' '269' '163' '172' '305' '156' '550' '435' '137' '124' '48'
 '279' '330' '5000' '134' '378' '97' '277' '64' '193' '147' '186' '264'
 '30' '3000' '112' '94' '379' '57' '415' '236' '410' '214' '88' '66' '71'
 '171' '157' '545' '1500' '83' '96' '1800' '81' '188' '380' '255' '505'
 '54' '33' '174' '93' '740' '640' '1300' '440' '599' '357' '1239' '495'
 '127' '5999' '178' '348' '152' '242' '183' '253' '750' '259' '365' '273'
 '197' '397' '103' '389' '355' '559' '38' '203' '999' '141' '162' '333'
 '698' '46' '360' '895' '10' '41' '206' '281' '449' '388' '212' '102'
 '201' '2750' '4750' '432' '675' '167' '390' '298' '339' '194' '302' '211'
 '595' '191' '53' '361' '480' '8000' '4500' '459' '997' '345' '216' '218'
 '111' '735' '276' '91' '490' '850' '398' '36' '775' '267' '625' '336'
 '2500' '176' '725' '3750' '469' '106' '460' '287' '575' '227' '263' '25'
 '228' '208' '177' '880' '148' '116' '685' '470' '217' '164' '61' '645'
 '699' '405' '252' '319' '268' '419' '343' '525' '311' '840' '154' '294'
 '950' '409' '184' '257' '204' '241' '2000' '412' '121' '288' '196' '900'
 '647' '524' '1750' '309' '510' '1495' '1700' '799' '383' '372' '492'
 '327' '1999' '656' '224' '173' '875' '1170' '795' '690' '146' '465'
 '1100' '151' '274' '429' '825' '282' '256' '1111' '620' '271' '161' '51'
 '855' '579' '1174' '430' '20' '899' '649' '485' '181' '455' '4000' '243'
 '342' '590' '560' '374' '437' '232' '359' '985' '31' '244' '254' '723'
 '237' '428' '370' '34' '1400' '580' '2520' '221' '749' '1600' '2695'
 '306' '202' '680' '570' '520' '223' '2295' '213' '1065' '346' '24' '286'
 '296' '266' '26' '995' '1368' '393' '182' '635' '258' '780' '589' '347'
 '1250' '1350' '446' '3200' '1050' '1650' '1550' '975' '323' '6500' '2499'
 '1850' '2250' '715' '461' '540' '356' '439' '384' '569' '1900' '22' '785'
 '626' '830' '318' '444' '321' '401' '1499' '888' '369' '770' '386' '366'
 '344' '630' '313' '597' '262' '509' '10000' '278' '312' '789' '1195'
 '422' '21' '765' '3500' '945' '326' '3100' '2486' '3390' '1356' '2599'
 '472' '454' '328' '396' '291']

[  145    37    28   199   549   149   250    90   270   290   170    59
    49    68   285    75   100   150   700   125   175    40    89    95
    99   499   120    79   110   180   143   230   350   135    85    60
    70    55    44   200   165   115    74    84   129    50   185    80
   190   140    45    65   225   600   109  1990    73   240    72   105
   155   160    42   132   117   295   280   159   107    69   239   220
   399   130   375   585   275   139   260    35   133   300   289   179
    98   195    29    27    39   249   192   142   169  1000   131   138
   113   122   329   101   475   238   272   308   126   235   315   248
   128    56   207   450   215   210   385   445   136   247   118    77
    76    92   198   205   299   222   245   104   153   349   114   320
   292   226   420   500   325   307    78   265   108   123   189    32
    58    86   219   800   335    63   229   425    67    87  1200   158
   650   234   310   695   400   166   119    62   168   340   479    43
   395   144    52    47   529   187   209   233    82   269   163   172
   305   156   550   435   137   124    48   279   330  5000   134   378
    97   277    64   193   147   186   264    30  3000   112    94   379
    57   415   236   410   214    88    66    71   171   157   545  1500
    83    96  1800    81   188   380   255   505    54    33   174    93
   740   640  1300   440   599   357  1239   495   127  5999   178   348
   152   242   183   253   750   259   365   273   197   397   103   389
   355   559    38   203   999   141   162   333   698    46   360   895
    10    41   206   281   449   388   212   102   201  2750  4750   432
   675   167   390   298   339   194   302   211   595   191    53   361
   480  8000  4500   459   997   345   216   218   111   735   276    91
   490   850   398    36   775   267   625   336  2500   176   725  3750
   469   106   460   287   575   227   263    25   228   208   177   880
   148   116   685   470   217   164    61   645   699   405   252   319
   268   419   343   525   311   840   154   294   950   409   184   257
   204   241  2000   412   121   288   196   900   647   524  1750   309
   510  1495  1700   799   383   372   492   327  1999   656   224   173
   875  1170   795   690   146   465  1100   151   274   429   825   282
   256  1111   620   271   161    51   855   579  1174   430    20   899
   649   485   181   455  4000   243   342   590   560   374   437   232
   359   985    31   244   254   723   237   428   370    34  1400   580
  2520   221   749  1600  2695   306   202   680   570   520   223  2295
   213  1065   346    24   286   296   266    26   995  1368   393   182
   635   258   780   589   347  1250  1350   446  3200  1050  1650  1550
   975   323  6500  2499  1850  2250   715   461   540   356   439   384
   569  1900    22   785   626   830   318   444   321   401  1499   888
   369   770   386   366   344   630   313   597   262   509 10000   278
   312   789  1195   422    21   765  3500   945   326  3100  2486  3390
  1356  2599   472   454   328   396   291]

Total missing:  0

2. Categorical variable: For the `./data/sharks.csv` data covered in the lecture, clean the "Type" variable as well as you can, and explain the choices you make.

In [7]:
df = pd.read_csv('/content/sharks.csv', low_memory=False)
df.head()

,index,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,...,Unnamed: 246,Unnamed: 247,Unnamed: 248,Unnamed: 249,Unnamed: 250,Unnamed: 251,Unnamed: 252,Unnamed: 253,Unnamed: 254,Unnamed: 255
0,0,2020.02.05,05-Feb-2020,2020.0,Unprovoked,USA,Maui,NaN,Stand-Up Paddle boarding,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020.01.30.R,Reported 30-Jan-2020,2020.0,Provoked,BAHAMAS,Exumas,NaN,Floating,Ana Bruna Avila,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2020.01.17,17-Jan-2020,2020.0,Unprovoked,AUSTRALIA,New South Wales,Windang Beach,Surfing,Will Schroeter,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2020.01.16,16-Jan-2020,2020.0,Unprovoked,NEW ZEALAND,Southland,Oreti Beach,Surfing,Jordan King,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020.01.13,13-Jan-2020,2020.0,Unprovoked,USA,North Carolina,"Rodanthe, Dare County",Surfing,Samuel Horne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df['Type'].value_counts()

Type
Unprovoked             4716
Provoked                593
Invalid                 552
Sea Disaster            239
Watercraft              142
Boat                    109
Boating                  92
Questionable             10
Unconfirmed               1
Unverified                1
Under investigation       1
Boatomg                   1
Name: count, dtype: int64

In [9]:
type = df['Type'] # Create a temporary vector of values for the Type variable to play with

type = type.replace(['Sea Disaster', 'Boat','Boating','Boatomg'],'Watercraft') # generalizes the type as watercraft so there are less variations
type.value_counts()

type = type.replace(['Invalid', 'Questionable','Unconfirmed','Unverified','Under investigation'],np.nan) # groups similar categories that are not final as under investigation
type.value_counts()

df['Type'] = type
del type
# Replace the old Type variable with the new cleaned version and gets rid of the old one

df['Type'].value_counts()

Type
Unprovoked    4716
Provoked       593
Watercraft     583
Name: count, dtype: int64

In [10]:
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].replace(['UNKNOWN', 'F','M','2017'],np.nan)
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].replace('y','Y')
pd.crosstab(df['Type'],df['Fatal (Y/N)'],normalize='index')
# Finally, this  replaces the above values with NaN and then creates a  cross-tab of event types and whether or not it was fatal

Fatal (Y/N)         N         Y
Type
Provoked     0.967521  0.032479
Unprovoked   0.743871  0.256129
Watercraft   0.684303  0.315697

3. Dummy variable: For the pretrial data covered in the lecture, clean the `WhetherDefendantWasReleasedPretrial` variable as well as you can, and, in particular, replace missing values with `np.nan`.

In [15]:
df = pd.read_csv('/content/VirginiaPretrialData2017.csv', low_memory=False)
df.head()

,InternalStudyID,REQ_REC#,Defendant_Sex,Defendant_Race,Defendant_BirthYear,Defendant_Age,Defendant_AgeGroup,Defendant_AgeatCurrentArrest,Defendant_AttorneyTypeAtCaseClosure,Defendant_IndigencyStatus,...,NewFelonySexualAssaultArrest_OffDate,NewFelonySexualAssaultArrest_ArrestDate,NewFelonySexualAssaultArrest_DaysBetweenContactEventandOffDate,NewFelonySexualAssaultArrest_DaysBetweenOffDateandArrestDate,NewFelonySexualAssaultArrest_DaysBetweenReleaseDateandOffDate,NewFelonySexualAssaultArrest_Disposition,Intertnalindicator_ReasonforExcludingFromFollowUpAnalysis,CriminalHistoryRecordsReturnedorCMSRecordsFoundforIndividual,DispRecordFoundforChargesinOct2017Contact_Atleast1dispfound,CrimeCommission2021ReportClassificationofDefendants
0,ADI00001,1,M,W,1986,31,3,31,99,99,...,,,,999,999,,4,1,0,Defendant could not be classified or tracked d...
1,ADI00007,3,M,B,1956,60,6,60,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
2,ADI00008,4,M,W,1990,27,3,27,9,9,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
3,CDI00036,6,M,B,1989,27,3,27,0,0,...,,,,999,999,,5,1,1,Defendant Detained Entire Pre-Trial Period_Und...
4,CDI00038,7,F,W,1988,28,3,28,0,0,...,,,,999,999,,0,1,1,New criminal offense punishable by incarcerati...

In [18]:
release = df['WhetherDefendantWasReleasedPretrial']
print(release.unique(),'\n')
print(release.value_counts(),'\n')
release = release.replace(9,np.nan)
print(release.value_counts(),'\n') # replaces the 9s with undefined values and prints it
sum(release.isnull()) # Sums the number of NaN values in the column
df['WhetherDefendantWasReleasedPretrial'] = release
del release # Replaces the original column with cleaned values and deletes the temporary variable

[nan  0.  1.]

WhetherDefendantWasReleasedPretrial
1.0    19154
0.0     3801
Name: count, dtype: int64

WhetherDefendantWasReleasedPretrial
1.0    19154
0.0     3801
Name: count, dtype: int64

4. Missing values, not at random: For the pretrial data covered in the lecture, clean the `ImposedSentenceAllChargeInContactEvent` variable as well as you can, and explain the choices you make. (Hint: Look at the `SentenceTypeAllChargesAtConvictionInContactEvent` variable.)

In [20]:
length = df['ImposedSentenceAllChargeInContactEvent']
type = df['SentenceTypeAllChargesAtConvictionInContactEvent']
length = pd.to_numeric(length,errors='coerce') # Converts values to numeric and errors become not a number
length_NA = length.isnull()
print( np.sum(length_NA),'\n') # prints the total number of missing values

print( pd.crosstab(length_NA, type), '\n') # Displays a cross-tab of missing values and sentence types

length = length.mask( type == 4, 0)
length = length.mask( type == 9, np.nan)
# Replaces length with 0 or not a number when charges were dismissed or n/a

length_NA = length.isnull() # Create a new missing dummy
print( pd.crosstab(length_NA, type), '\n')
print( np.sum(length_NA),'\n') # cleans the data so that there are significantly less missing

df['ImposedSentenceAllChargeInContactEvent'] = length # Replaces data with the cleaned version
del length, type # Delete length and type variables that aren't relevant anymore

274

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

SentenceTypeAllChargesAtConvictionInContactEvent     0     1    2     4    9
ImposedSentenceAllChargeInContactEvent
False                                             8720  4299  914  8779    0
True                                                 0     0    0     0  274

274